name: Lint
on: [push, pull_request]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install ESLint v7
        run: npm install eslint@7

      - name: Install ESLint Configs and Plugins
        run: npm install -D eslint-plugin-import eslint-plugin-node eslint-plugin-unicorn

      - name: Run ESLint
        run: npm run lint
